"import { Component, OnInit } from '@angular/core';",
" ",
"import { LogService } from '../services/logService';",
"import { OfficeService } from '../services/officeService';",
"import { CrmService } from '../services/crmService';",
"import { ICustomer } from '../../../shared/models/ICustomer';",
" ",
"@Component({",
"  moduleId: module.id,",
"  selector: 'minicrm-customer-list',",
"  templateUrl: 'customer-list.component.html',",
"  styleUrls: ['customer-list.component.css']",
"})",
"export class CustomerListComponent implements OnInit {",
"  public lookupCandidates: ICustomer[] = [];",
" ",
"  constructor(private logService: LogService,",
"              private officeService: OfficeService,",
"              private crmService: CrmService) {",
"  }",
" ",
"  public ngOnInit() {",
"    this.logService.info('ngOnInit: CustomerListComponent');",
" ",
"    // lookup customers from currently selected email",
"    this.loadMatchesFromEmail();",
"  }",
" ",
"  private loadMatchesFromEmail(): void {",
"    this.officeService.getWordCandidatesFromEmail()",
"      .then((candidates: string[]) => {",
"        this.crmService.lookupCustomerPartials(candidates)",
"          .then((results: ICustomer[]) => {",
"            this.lookupCandidates = results;",
"          });",
"      });",
"  }",
" ",
"  private getCustomerInitials(customer: ICustomer): string {",
"    return customer.name.replace(/[a-z]/g, '').replace(' ', '');",
"  }",
"}"